/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NkDropkit {
        /**
          * Drop SDK Key
         */
        "apikey": string;
        /**
          * Flag to enable testnet mode
         */
        "dev": boolean;
        /**
          * Flag to enable multiple wallet support
         */
        "multiple": boolean;
    }
}
declare global {
    interface HTMLNkDropkitElement extends Components.NkDropkit, HTMLStencilElement {
    }
    var HTMLNkDropkitElement: {
        prototype: HTMLNkDropkitElement;
        new (): HTMLNkDropkitElement;
    };
    interface HTMLElementTagNameMap {
        "nk-dropkit": HTMLNkDropkitElement;
    }
}
declare namespace LocalJSX {
    interface NkDropkit {
        /**
          * Drop SDK Key
         */
        "apikey"?: string;
        /**
          * Flag to enable testnet mode
         */
        "dev"?: boolean;
        /**
          * Flag to enable multiple wallet support
         */
        "multiple"?: boolean;
    }
    interface IntrinsicElements {
        "nk-dropkit": NkDropkit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nk-dropkit": LocalJSX.NkDropkit & JSXBase.HTMLAttributes<HTMLNkDropkitElement>;
        }
    }
}
